spring:
  datasource:
    url: jdbc:sqlite:./Coco.db
    username:
    password:
    driver-class-name: org.sqlite.JDBC
    sql-script-encoding: UTF-8
    continue-on-error: false
    schema:
      - classpath:sqls/0.0.1/schema.sql
    initialization-mode: always
    hikari:
      minimum-idle: 10
      maximum-pool-size: 15
      idle-timeout: 60000